spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: product-service

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      resilience4j: true