spring:
  application:
    name: order-service
  config:
    import: optional:configserver:http://localhost:8888

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      resilience4j: true
